# generated by xuyunkai`s SysY compiler.
	.section	.rodata
.LC0:
	.string	"%d\n"
	.text
	.globl	main
	.type	main, @function
main:
	pushl	%ebp
	movl	%esp, %ebp
	subl	$60, %esp
	movl	$6, %eax
	pushl	%eax
	movl	$2, %eax
	popl	%ebx
	movl	%ebx, -12(%ebp,%eax,4)
	movl	$2, %eax
	pushl	%eax
	movl	$1, %eax
	popl	%ebx
	movl	%ebx, -12(%ebp,%eax,4)
	movl	$2, %eax
	pushl	%eax
	movl	$0, %eax
	pushl	%eax
	movl	$3, %eax
	popl	%ebx
	imull	%ebx, %eax
	pushl	%eax
	movl	$1, %eax
	popl	%ebx
	addl	%ebx, %eax
	popl	%ebx
	movl	%ebx, -28(%ebp,%eax,4)
	movl	$3, %eax
	pushl	%eax
	movl	$1, %eax
	pushl	%eax
	movl	$3, %eax
	popl	%ebx
	imull	%ebx, %eax
	pushl	%eax
	movl	$2, %eax
	popl	%ebx
	addl	%ebx, %eax
	popl	%ebx
	movl	%ebx, -28(%ebp,%eax,4)
	movl	$2, %eax
	movl	-12(%ebp,%eax,4), %eax
	movl	%eax, -52(%ebp)
	movl	$1, %eax
	movl	-12(%ebp,%eax,4), %eax
	movl	%eax, -56(%ebp)
	movl	-52(%ebp), %eax
	pushl	%eax
	movl	-56(%ebp), %eax
	popl	%ebx
	addl	%ebx, %eax
	movl	%eax, -52(%ebp)
	movl	-52(%ebp), %eax
	pushl	%eax
	movl	$.LC0, %eax
	pushl	%eax
	call	printf
	addl	$8, %esp
	movl	$0, %eax
	pushl	%eax
	movl	$3, %eax
	popl	%ebx
	imull	%ebx, %eax
	pushl	%eax
	movl	$1, %eax
	popl	%ebx
	addl	%ebx, %eax
	movl	-28(%ebp,%eax,4), %eax
	pushl	%eax
	movl	$1, %eax
	pushl	%eax
	movl	$3, %eax
	popl	%ebx
	imull	%ebx, %eax
	pushl	%eax
	movl	$2, %eax
	popl	%ebx
	addl	%ebx, %eax
	movl	-28(%ebp,%eax,4), %eax
	popl	%ebx
	addl	%ebx, %eax
	movl	%eax, -52(%ebp)
	movl	-52(%ebp), %eax
	pushl	%eax
	movl	$.LC0, %eax
	pushl	%eax
	call	printf
	addl	$8, %esp
	movl	$0, %eax
	jmp		.LRET_main
.LRET_main:
	addl	$60, %esp
	popl	%ebp
	ret
	.ident	"LuczyCompiler: (Ubuntu 1.0.0ubuntu1~18.04) 1.0.0"
	.section .note.GNU-stack,"",@progbits
