# generated by xuyunkai`s SysY compiler.
	.section	.rodata
.LC0:
	.string	"%d %d\n"
	.text
	.globl	main
	.type	main, @function
main:
	pushl	%ebp
	movl	%esp, %ebp
	subl	$28, %esp
	movl	$1, %eax
	movl	%eax, -12(%ebp)
	movl	$1, %eax
	movl	%eax, -16(%ebp)
	movl	$2, %eax
	movl	%eax, -24(%ebp)
.L0:
	movl	-24(%ebp), %eax
	pushl	%eax
	movl	$20, %eax
	popl	%ebx
	cmpl	%eax, %ebx
	setl	%al
	jl		.L1
	jmp		.L2
.L1:
	movl	-12(%ebp), %eax
	movl	%eax, -20(%ebp)
	movl	-12(%ebp), %eax
	pushl	%eax
	movl	-16(%ebp), %eax
	popl	%ebx
	addl	%ebx, %eax
	movl	%eax, -12(%ebp)
	movl	-20(%ebp), %eax
	movl	%eax, -16(%ebp)
.L3:
	movl	-24(%ebp), %eax
	incl	-24(%ebp)
	jmp		.L0
.L2:
	movl	-16(%ebp), %eax
	pushl	%eax
	movl	-12(%ebp), %eax
	pushl	%eax
	movl	$.LC0, %eax
	pushl	%eax
	call	printf
	addl	$12, %esp
	movl	$0, %eax
	jmp		.LRET_main
.LRET_main:
	addl	$28, %esp
	popl	%ebp
	ret
	.ident	"LuczyCompiler: (Ubuntu 1.0.0ubuntu1~18.04) 1.0.0"
	.section .note.GNU-stack,"",@progbits
