# generated by xuyunkai`s SysY compiler.
	.section	.rodata
.LC0:
	.string	"%d\n"
	.text
	.globl	main
	.type	main, @function
main:
	pushl	%ebp
	movl	%esp, %ebp
	subl	$28, %esp
	movl	$50, %eax
	movl	%eax, -12(%ebp)
	movl	$1, %eax
	negl	%eax
	movl	%eax, -16(%ebp)
	movl	$0, %eax
	movl	%eax, -20(%ebp)
.L0:
	movl	-20(%ebp), %eax
	pushl	%eax
	movl	-12(%ebp), %eax
	pushl	%eax
	movl	$2, %eax
	popl	%ebx
	imull	%ebx, %eax
	popl	%ebx
	cmpl	%eax, %ebx
	setl	%al
	jl		.L1
	jmp		.L2
.L1:
	movl	$0, %eax
	movl	%eax, -24(%ebp)
.L4:
	movl	-24(%ebp), %eax
	pushl	%eax
	movl	-12(%ebp), %eax
	popl	%ebx
	cmpl	%eax, %ebx
	setl	%al
	jl		.L5
	jmp		.L6
.L5:
.L8:
	movl	-24(%ebp), %eax
	pushl	%eax
	movl	-12(%ebp), %eax
	pushl	%eax
	movl	$2, %eax
	movl	%eax, %ebx
	popl	%eax
	cltd
	idivl	%ebx
	popl	%ebx
	cmpl	%eax, %ebx
	setl	%al
	jl		.L12
	jmp		.L10
	pushl	%eax
.L12:
	movl	-24(%ebp), %eax
	pushl	%eax
	movl	$2, %eax
	movl	%eax, %ebx
	popl	%eax
	cltd
	idivl	%ebx
	movl	%edx, %eax
	pushl	%eax
	movl	$0, %eax
	popl	%ebx
	cmpl	%eax, %ebx
	setne	%al
	jne		.L9
	jmp		.L10
	popl	%ebx
	andl	%eax, %ebx
	setne	%al
.L9:
	movl	-16(%ebp), %eax
	pushl	%eax
	movl	-20(%ebp), %eax
	pushl	%eax
	movl	-24(%ebp), %eax
	popl	%ebx
	imull	%ebx, %eax
	pushl	%eax
	movl	$2, %eax
	movl	%eax, %ebx
	popl	%eax
	cltd
	idivl	%ebx
	popl	%ebx
	addl	%ebx, %eax
	pushl	%eax
	movl	-20(%ebp), %eax
	pushl	%eax
	movl	-24(%ebp), %eax
	popl	%ebx
	imull	%ebx, %eax
	popl	%ebx
	addl	%ebx, %eax
	movl	%eax, -16(%ebp)
	jmp		.L11
.L10:
.L13:
	movl	-16(%ebp), %eax
	pushl	%eax
	movl	-24(%ebp), %eax
	popl	%ebx
	cmpl	%eax, %ebx
	setg	%al
	jg		.L14
	jmp		.L16
	pushl	%eax
.L16:
	movl	-16(%ebp), %eax
	pushl	%eax
	movl	$0, %eax
	popl	%ebx
	cmpl	%eax, %ebx
	setne	%al
	jne		.L15
	jmp		.L14
	popl	%ebx
	orb	%al, %bl
	setne	%al
.L14:
	movl	-16(%ebp), %eax
	pushl	%eax
	movl	$3, %eax
	pushl	%eax
	movl	$2, %eax
	movl	%eax, %ebx
	popl	%eax
	cltd
	idivl	%ebx
	movl	%eax, %ebx
	popl	%eax
	subl	%ebx, %eax
	movl	%eax, -16(%ebp)
	jmp		.L13
.L15:
.L11:
.L7:
	movl	-24(%ebp), %eax
	incl	-24(%ebp)
	jmp		.L4
.L6:
.L3:
	movl	-20(%ebp), %eax
	incl	-20(%ebp)
	jmp		.L0
.L2:
	movl	-16(%ebp), %eax
	pushl	%eax
	movl	$.LC0, %eax
	pushl	%eax
	call	printf
	addl	$8, %esp
	movl	$0, %eax
	jmp		.LRET_main
.LRET_main:
	addl	$28, %esp
	popl	%ebp
	ret
	.ident	"LuczyCompiler: (Ubuntu 1.0.0ubuntu1~18.04) 1.0.0"
	.section .note.GNU-stack,"",@progbits
