# generated by xuyunkai`s SysY compiler.
	.section	.rodata
.LC0:
	.string	"%d\n"
	.text
	.globl	fib
	.type	fib, @function
fib:
	pushl	%ebp
	movl	%esp, %ebp
	subl	$12, %esp
.L0:
	movl	8(%ebp), %eax
	pushl	%eax
	movl	$1000, %eax
	popl	%ebx
	cmpl	%eax, %ebx
	setg	%al
	jg		.L1
	jmp		.L2
.L1:
	movl	8(%ebp), %eax
	pushl	%eax
	movl	12(%ebp), %eax
	popl	%ebx
	imull	%ebx, %eax
	pushl	%eax
	movl	$5, %eax
	movl	%eax, %ebx
	popl	%eax
	cltd
	idivl	%ebx
	movl	%edx, %eax
	pushl	%eax
	movl	$1, %eax
	negl	%eax
	movl	%eax, %ebx
	popl	%eax
	subl	%ebx, %eax
	jmp		.LRET_fib
.L2:
	movl	8(%ebp), %eax
	pushl	%eax
	movl	8(%ebp), %eax
	pushl	%eax
	movl	12(%ebp), %eax
	popl	%ebx
	addl	%ebx, %eax
	pushl	%eax
	call	fib
	addl	$8, %esp
	pushl	%eax
	movl	$1, %eax
	popl	%ebx
	addl	%ebx, %eax
	jmp		.LRET_fib
.LRET_fib:
	addl	$12, %esp
	popl	%ebp
	ret
	.globl	main
	.type	main, @function
main:
	pushl	%ebp
	movl	%esp, %ebp
	subl	$12, %esp
	movl	$1, %eax
	pushl	%eax
	movl	$1, %eax
	pushl	%eax
	call	fib
	addl	$8, %esp
	pushl	%eax
	movl	$.LC0, %eax
	pushl	%eax
	call	printf
	addl	$8, %esp
	movl	$0, %eax
	jmp		.LRET_main
.LRET_main:
	addl	$12, %esp
	popl	%ebp
	ret
	.ident	"LuczyCompiler: (Ubuntu 1.0.0ubuntu1~18.04) 1.0.0"
	.section .note.GNU-stack,"",@progbits
