# generated by xuyunkai`s SysY compiler.
	.section	.rodata
.LC0:
	.string	"%d\n"
	.text
	.globl	main
	.type	main, @function
main:
	pushl	%ebp
	movl	%esp, %ebp
	subl	$32, %esp
	movl	$2, %eax
	movl	%eax, -12(%ebp)
	movl	$3, %eax
	movl	%eax, -16(%ebp)
	movl	-12(%ebp), %eax
	pushl	%eax
	movl	$.LC0, %eax
	pushl	%eax
	call	printf
	addl	$8, %esp
	movl	-16(%ebp), %eax
	pushl	%eax
	movl	$.LC0, %eax
	pushl	%eax
	call	printf
	addl	$8, %esp
	leal	-12(%ebp), %eax
	movl	%eax, -20(%ebp)
	leal	-16(%ebp), %eax
	movl	%eax, -24(%ebp)
	movl	-24(%ebp), %eax
	movl	(%eax), %eax
	movl	%eax, -28(%ebp)
	movl	-20(%ebp), %eax
	movl	%eax, -24(%ebp)
	movl	-28(%ebp), %eax
	pushl	%eax
	movl	-24(%ebp), %eax
	movl	(%eax), %eax
	popl	%ebx
	imull	%ebx, %eax
	pushl	%eax
	movl	-20(%ebp), %eax
	movl	(%eax), %eax
	popl	%ebx
	imull	%ebx, %eax
	pushl	%eax
	movl	-24(%ebp), %eax
	movl	(%eax), %eax
	movl	%eax, %ebx
	popl	%eax
	cltd
	idivl	%ebx
	movl	%eax, -28(%ebp)
	movl	-20(%ebp), %eax
	movl	(%eax), %eax
	pushl	%eax
	movl	$.LC0, %eax
	pushl	%eax
	call	printf
	addl	$8, %esp
	movl	-24(%ebp), %eax
	movl	(%eax), %eax
	pushl	%eax
	movl	$.LC0, %eax
	pushl	%eax
	call	printf
	addl	$8, %esp
	movl	-28(%ebp), %eax
	pushl	%eax
	movl	$.LC0, %eax
	pushl	%eax
	call	printf
	addl	$8, %esp
	movl	$0, %eax
	jmp		.LRET_main
.LRET_main:
	addl	$32, %esp
	popl	%ebp
	ret
	.ident	"LuczyCompiler: (Ubuntu 1.0.0ubuntu1~18.04) 1.0.0"
	.section .note.GNU-stack,"",@progbits
